import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'
import { Topic } from '@/types/serverData.type'

export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by nijuy',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const response = await fetch('http://localhost:9999/topics')
  const topics = await response.json()

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic: Topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create"> create </Link>
          </li>
          <li>
            <Link href="/update/id"> update </Link>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  )
}
