import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'
import { Topic } from '@/types/serverData.type'
import { Control } from './Control'

export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by nijuy',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/topics`, {
    cache: 'no-store',
  })
  const topics = await response.json()

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic: Topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
